"use client";
import Link from 'next/link';
import type {LucideIcon} from 'lucide-react';
import {ArrowUpRight, RefreshCw, Inbox} from 'lucide-react';
export function PortalHero({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:{label:string;href:string}}){return <section className="cw-hero"><div className="relative z-[1] flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="cw-eyebrow">{eyebrow}</div><h1 className="mt-3">{title}</h1><p className="mt-3 max-w-xl">{description}</p></div>{action&&<Link href={action.href} className="cw-primary shrink-0 self-start sm:self-end">{action.label}<ArrowUpRight size={16}/></Link>}</div></section>}
export function MetricCard({label,value,note,icon:Icon}:{label:string;value:string|number;note:string;icon:LucideIcon}){return <article className="cw-metric"><div className="flex items-start justify-between gap-2"><span className="cw-metric-label">{label.toUpperCase()}</span><span className="cw-action-icon"><Icon size={18}/></span></div><div className="cw-metric-value mt-2 tabular-nums">{value}</div><p className="cw-metric-note mt-1">{note}</p></article>}
export function ModuleAction({href,label,description,icon:Icon}:{href:string;label:string;description:string;icon:LucideIcon}){return <Link href={href} className="cw-action"><span className="cw-action-icon"><Icon size={19}/></span><span className="flex-1 min-w-0"><span className="cw-action-label block">{label}</span><span className="cw-action-description block">{description}</span></span><ArrowUpRight size={15} className="shrink-0" color="var(--cw-muted)"/></Link>}
export function DataEmpty({title,description}:{title:string;description:string}){return <div className="cw-empty"><Inbox size={23} color="var(--cw-accent)"/><strong>{title}</strong><p>{description}</p></div>}
export function DataError({message,onRetry}:{message?:string;onRetry:()=>void}){return <div className="cw-error flex flex-wrap items-center justify-between gap-3" role="alert"><span>{message||'We could not load this live information. No placeholder figures are shown.'}</span><button type="button" className="cw-secondary-button" onClick={onRetry}><RefreshCw size={14}/>Retry</button></div>}
export function DashboardSection({eyebrow,title,description,children}:{eyebrow:string;title:string;description?:string;children:React.ReactNode}){return <section className="cw-card"><div className="cw-eyebrow">{eyebrow}</div><h2 className="cw-card-title mt-2">{title}</h2>{description&&<p className="cw-card-description mt-2">{description}</p>}<div className="mt-5">{children}</div></section>}
