/** Static SVG preview paths for template gallery (generated by scripts/generate-template-previews.mjs) */
export function getTemplatePreviewPath(templateId) {
  if (!templateId) return null
  return `/templates/previews/${templateId}.svg`
}

export function withTemplatePreview(template) {
  if (!template?.id) return template
  return { ...template, preview: getTemplatePreviewPath(template.id) }
}
